# Change these first
owner: acm-uic # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ACM@UIC Website acm-uic.github.io
    url: https://acm-uic.github.io
  - name: ACM@UIC Website acmuic.org
    url: https://acmuic.org
  - name: ACM@UIC Website acm.cs.uic.edu
    url: https://acm.cs.uic.edu
  - name: Plausible Analytics
    url: https://plausible.acmuic.org/api/health
  - name: ACM@UIC Website Typesense
    url: https://typesense.acmuic.org/health
  - name: Pathfinder
    url: https://umpf.acmuic.org
  - name: Oven Temp
    url: https://oventemp.acmuic.org/api/health
  - name: LUG@UIC website lug.cs.uic.edu
    url: https://lug.cs.uic.edu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: upptime.acmuic.app
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/acm-uic/upptime/master/assets/upptime-icon.svg
  name: Upptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
